net/bnx2x: use RTE_BIT32
The expression "0x1 << 31" is actually undefined since 0x1
is an integer not unsigned. Fix the general problem by using
the existing RTE_BIT32() macros instead.

Shows up as a cryptic warning when building with -Dbsanitize=undefined.

../drivers/net/bnx2x/bnx2x.c:3362:25: error: case label does not reduce to an integer constant
 3362 |                         case AEU_INPUTS_ATTN_BITS_MCP_LATCHED_SCPAD_PARITY:
      |                         ^~~~

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>